version: '3.3'

services:
  db:
    image: postgres:14.1-alpine
    command: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql
      - /home/ubuntu/src/docker/config/db/dbinit.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    env_file:
      - ./src/docker/config/db/db.conf
    deploy:
      resources:
        limits:
          memory: 6gb
        reservations:
          memory: 3gb
  app:
    build: .
    restart: always
    depends_on:
      - db
    volumes:
      - /home/ubuntu/src/main/resources/static:/src/main/resources/static
    ports:
      - "8080:8080"
    env_file:
      - ./src/docker/config/app/app.conf
    deploy:
      resources:
        limits:
          memory: 4gb
        reservations:
          memory: 2gb
volumes:
  postgres-data:
    external: false
