server:
  servlet:
    context-path: /api
  port: 8080
  tomcat:
    max-swallow-size: 100MB
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:keystore/tok_zhzni.p12
#    key-store-password: 123456
#    key-alias: tok_zhizni
#    enabled: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tok_zhizni?reWriteBatchedInserts=true
    username: tz_app
    password: password
    hikari:
      schema: api_data
  liquibase:
    default-schema: api_data
  security:
    user:
      name: admin
      password: password
      roles: ROLE_ADMIN ROLE_USER
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org.apache: debug
    org.springframework.web: debug
