package ru.mospolytech.tok_zhizni.repository

import ru.mospolytech.tok_zhizni.entity.domain.Manufacturer
import ru.mospolytech.tok_zhizni.entity.domain.ManufacturerCreateRequest
import ru.mospolytech.tok_zhizni.entity.domain.ManufacturerUpdateRequest

interface ManufacturersRepository: CrudRepository<ManufacturerCreateRequest, ManufacturerUpdateRequest,Manufacturer>